### PR TITLE
2/2 Fix idempotence implementation

### LINKED ISSUE #1: Unsafe `DefaultIdemFunc`
The [`DefaultIdemFunc`](https://github.com/CopilotIQ/stannp-client-golang/blob/274671994c81c28021238dbd9b8a19526c6d6883/stannp/stannp.go#L23-L30) seems unsafe. For instance, a caller retrying an errored request would result in a different idempotency key being generated and used for the `X-Idempotency-Key` header.

Given the current interface, I'm not sure that you can safely generate an idempotency key as the function is provided at the time of the stannp api client being instantiated and no context about the request is passed into it.

An alternate interface that might be more useful would be to have the methods which post (`SendLetter`, `ValidateAddress`) accept functional options, one of which injects an idempotency key. This would give callers of `SendLetter` a way to provide a uuid **at the time of calling** which remains the same for any arbitrary number of retries.

Something along the lines of:
```diff
diff --git a/stannp/stannp.go b/stannp/stannp.go
index e964c8d..8e50370 100644
--- a/stannp/stannp.go
+++ b/stannp/stannp.go
@@ -115,7 +116,24 @@ func (s *Stannp) wrapAuth(inputURL string) (string, *util.APIError) {
 	return u.String(), nil
 }
 
-func (s *Stannp) post(inputReader io.Reader, inputURL string) (*http.Response, *util.APIError) {
+type postOptions struct {
+	idempotencyKey string
+}
+
+type PostOptionFn func(po *postOptions)
+
+func WithIdempotencyKey(idempotencyKey string) PostOptionFn {
+	return func(po *postOptions) {
+		po.idempotencyKey = idempotencyKey
+	}
+}
+
+func (s *Stannp) post(inputReader io.Reader, inputURL string, optionFns ...PostOptionFn) (*http.Response, *util.APIError) {
+	opts := &postOptions{}
+	for _, optionFn := range optionFns {
+		optionFn(opts)
+	}
+
 	authURL, wrapErr := s.wrapAuth(inputURL)
 	if wrapErr != nil {
 		return nil, wrapErr
@@ -128,8 +146,8 @@ func (s *Stannp) post(inputReader io.Reader, inputURL string) (*http.Response, *
 
 	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
 
-	if s.idemFunc != nil {
-		req.Header.Set("X-Idempotency-Key", s.idemFunc())
+	if len(opts.idempotencyKey) > 0 {
+		req.Header.Set("X-Idempotency-Key", opts.idempotencyKey)
 	}
 
 	res, err := s.client.Do(req)
@@ -140,7 +158,7 @@ func (s *Stannp) post(inputReader io.Reader, inputURL string) (*http.Response, *
 	return res, nil
 }
 
-func (s *Stannp) SendLetter(request *letter.SendReq) (*letter.SendRes, *util.APIError) {
+func (s *Stannp) SendLetter(request *letter.SendReq, optionFns ...PostOptionFn) (*letter.SendRes, *util.APIError) {
 	formData := url.Values{}
 	formData.Set("clearzone", strconv.FormatBool(s.clearZone))
 	formData.Set("duplex", strconv.FormatBool(s.duplex))
@@ -162,7 +180,7 @@ func (s *Stannp) SendLetter(request *letter.SendReq) (*letter.SendRes, *util.API
 		formData.Set("recipient["+key+"]", value)
 	}
 
-	res, postErr := s.post(strings.NewReader(formData.Encode()), strings.Join([]string{s.baseUrl, letter.URL, CreateURL}, "/"))
+	res, postErr := s.post(strings.NewReader(formData.Encode()), strings.Join([]string{s.baseUrl, letter.URL, CreateURL}, "/"), optionFns...)
 	if postErr != nil {
 		return nil, postErr
 	}
@@ -172,7 +190,7 @@ func (s *Stannp) SendLetter(request *letter.SendReq) (*letter.SendRes, *util.API
 	return &letterRes, resErr
 }
 
-func (s *Stannp) ValidateAddress(request *address.ValidateReq) (*address.ValidateRes, *util.APIError) {
+func (s *Stannp) ValidateAddress(request *address.ValidateReq, optionFns ...PostOptionFn) (*address.ValidateRes, *util.APIError) {
 	// Create URL values
 	formData := url.Values{}
 	formData.Set("company", request.Company)
@@ -182,7 +200,7 @@ func (s *Stannp) ValidateAddress(request *address.ValidateReq) (*address.Validat
 	formData.Set("zipcode", request.Zipcode)
 	formData.Set("country", request.Country)
 
-	res, postErr := s.post(strings.NewReader(formData.Encode()), strings.Join([]string{s.baseUrl, address.URL, ValidateURL}, "/"))
+	res, postErr := s.post(strings.NewReader(formData.Encode()), strings.Join([]string{s.baseUrl, address.URL, ValidateURL}, "/"), optionFns...)
 	if postErr != nil {
 		return nil, postErr
 	}
```

### PR DESCRIPTION
**Pull request by seantcanavan**
Closes #1

### CODE REVIEW

File: stannp/stannp_test.go [hunk 1]
```diff
@@ -53,43 +56,73 @@ func setup() {
...
+
+		// in golang this closes the response writer automagically
+		w.Header().Set("Content-Type", "application/json")
+	}
+
+	ts := httptest.NewServer(http.HandlerFunc(handler))
+
+	api := New(
+		WithAPIKey(apiKey),
+		WithHTTPClient(ts.Client()),
```
Comment (seantcanavan) [inline stannp/stannp_test.go:109]: shoutout @dillonstreator for making this possible - perfect timing too to test the idempotencey key fixes!
